In [1]:
import numpy as np


In [4]:
a = np.zeros((3, 3, 3))
for i in range(3):
    for j in range(3):
        for k in range(3):
            a[i,j,k] = i + k + j
a

array([[[0., 1., 2.],
        [1., 2., 3.],
        [2., 3., 4.]],

       [[1., 2., 3.],
        [2., 3., 4.],
        [3., 4., 5.]],

       [[2., 3., 4.],
        [3., 4., 5.],
        [4., 5., 6.]]])

In [8]:
a = np.average(a, axis=1)
np.average(a, axis=1)

array([2., 3., 4.])

In [13]:
np.vstack(np.random.choice([-1., 1.], size=(3))

array([-1.,  1., -1.])